[ids]
05ac:0343:89b7fedc

include ru

[global]
default_layout = en

# English layout (main mappings would override the ru layout)
[en:layout]
` = ~
capslock = esc

# Esc in ru switches to en (e.g. before typing the lock-screen password)
[ru]
capslock = setlayout(en)

[main]
rightmeta = layer(symbols)

d+f = {
j+k = }
p+o = macro(( ) left)
c+v = macro(C-/)
j+enter = macro(escape S-a ; escape)
k+enter = macro(escape S-a , escape)

[symbols]
` = ~

tab = ~
q = '
w = =
e = {
r = }
t = "
y = ~
u = _
i = |
o = \
p = +
backspace = backspace

capslock = :
a = &
s = /
d = (
f = )
g = @
h = #
j = $
k = !
l = *
enter = ;

z = %
x = ^
c = [
v = ]
b = `
n = -
m = *
, = ,
. = .
/ = ?
rightshift = rightshift

meta = <
alt = >
space = space

1 = !
2 = @
3 = #
4 = $
5 = %

leftcontrol = \

