[ids]

258a:000c

include ru_gpd

[main]
capslock = esc
` = ~
; = layer(symbols)
rightalt = layer(symbols)
leftalt = layer(symbols)

d+f = {
j+k = }
p+o = macro(( ) left)
c+v = macro(C-/)
j+enter = macro(escape S-a ; escape)
k+enter = macro(escape S-a , escape)

[to_ru]
space = setlayout(ru)

[symbols]
` = ~

tab = ~
q = '
w = =
e = {
r = }
t = "
y = ~
u = _
i = |
o = \
p = +
backspace = backspace

capslock = :
a = &
s = /
d = (
f = )
g = @
h = #
j = $
k = !
l = *
enter = ;  

leftshift = leftshift
z = %
x = ^
c = [
v = ]
b = `
n = -
m = *
, = ,
. = .
/ = ?
rightshift = rightshift

meta = <
alt = >
space = space

1 = !
2 = @
3 = #
4 = $
5 = %

leftcontrol = \

